const currencySymbols: Record<string, string> = {
  USD: "$",
  EUR: "€",
  GBP: "£",
  JPY: "¥",
  CNY: "¥",
  CHF: "Fr",
  CAD: "C$",
  AUD: "A$",
  MXN: "$",
  BRL: "R$",
  ARS: "$",
  COP: "$",
  CLP: "$",
  PEN: "S/",
  INR: "₹",
  KRW: "₩",
  RUB: "₽",
  TRY: "₺",
  PLN: "zł",
  SEK: "kr",
  NOK: "kr",
  DKK: "kr",
  NZD: "NZ$",
  SGD: "S$",
  HKD: "HK$",
  ZAR: "R",
  THB: "฿",
  IDR: "Rp",
  MYR: "RM",
  PHP: "₱",
  VND: "₫",
  EGP: "E£",
  ILS: "₪",
  AED: "د.إ",
  SAR: "﷼",
}

export const getCurrencySymbol = (badge: string): string => {
  return currencySymbols[badge.toUpperCase()] ?? badge
}
